const fs = require('fs');
const path = require('path');

console.log('--- RC-99 Vercel Production Build Starting ---');

// 1. Read Environment Variables from Vercel build environment
const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

console.log(`Supabase URL configured in build: ${supabaseUrl ? supabaseUrl.replace(/(https:\/\/[^.]+).*/, '$1.supabase.co') : 'NOT SET'}`);
console.log(`Supabase Anon Key configured in build: ${supabaseAnonKey ? '✓ Present (' + supabaseAnonKey.substring(0, 10) + '...)' : 'NOT SET'}`);

// 2. Generate js/supabase-config.js with injected credentials
const configJsContent = `/**
 * Supabase Client Configuration for RC-99 Platform
 * Auto-generated by Vercel Production Build.
 */

(function () {
  'use strict';

  // Injected credentials from Vercel Environment Variables
  const BUILD_SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
  const BUILD_SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey)};

  // Check localStorage for custom override if set via browser UI
  let userConfig = null;
  try {
    const stored = localStorage.getItem('rc99_supabase_config');
    if (stored) userConfig = JSON.parse(stored);
  } catch (e) {}

  const activeUrl = (userConfig && userConfig.url) || window.SUPABASE_URL || BUILD_SUPABASE_URL;
  const activeAnonKey = (userConfig && userConfig.anonKey) || window.SUPABASE_ANON_KEY || BUILD_SUPABASE_ANON_KEY;

  // Validation function: returns true ONLY when a real valid Supabase project is active
  window.isSupabaseActive = function () {
    return !!(
      window.supabaseClient &&
      activeUrl &&
      activeUrl.startsWith('https://') &&
      activeUrl.includes('.supabase.co') &&
      activeAnonKey &&
      activeAnonKey.length > 30
    );
  };

  // Initialize Supabase Client
  if (window.supabase && typeof window.supabase.createClient === 'function') {
    if (activeUrl && activeAnonKey && activeUrl.startsWith('https://') && activeAnonKey.length > 30) {
      try {
        window.supabaseClient = window.supabase.createClient(activeUrl, activeAnonKey, {
          auth: {
            persistSession: true,
            autoRefreshToken: true,
            detectSessionInUrl: true,
            storage: window.localStorage
          }
        });
        console.log('✓ Supabase Client active on: ' + activeUrl);
      } catch (err) {
        console.error('Supabase initialization failed:', err);
        window.supabaseClient = null;
      }
    } else {
      window.supabaseClient = null;
      console.log('ℹ Supabase is unconfigured. Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel to activate cloud authentication.');
    }
  } else {
    window.supabaseClient = null;
  }

})();
`;

// Write to both js/ and dist/js/
fs.writeFileSync(path.join(__dirname, 'js', 'supabase-config.js'), configJsContent);

if (fs.existsSync(path.join(__dirname, 'dist', 'js'))) {
  fs.writeFileSync(path.join(__dirname, 'dist', 'js', 'supabase-config.js'), configJsContent);
}

// Copy other static files to dist/ if needed
if (!fs.existsSync(path.join(__dirname, 'dist'))) {
  fs.mkdirSync(path.join(__dirname, 'dist'));
}

console.log('✓ Injected Supabase configuration successfully.');
console.log('--- RC-99 Vercel Production Build Completed ---');
